### ISSUE TITLE
TODO: 3 Dec

### ISSUE THREAD

**Issue by jyu283** [jyu283/edoras#5]
- [x] Collision Detection: Game over state. @jyu283
- [x] Jump Physics: More playable jumping acceleration. @jyu283
- [x] Obstacle Generation: Multiple Cacti on horizon. @Cai-Fangxu 
- [x] Obstacle Generation: Birds. @CarolYeh910 
- [x] Ducking Mechanism: Event handler for Down Key-press event. @ERRUI 
- [x] Score keeping, difficulty, and general UI improvements. @CarolYeh910 
- [x] Game start screen + Game over screen. (Key triggered (space) for now) @ERRUI 

Game start/end screen: freeze movements + message box ("press any key to start"/"GAME OVER, press any key to restart") restart = reset ticks <=> reset score.
